### PR TITLE
Add option to use Asynchronous loading of connection data.

### PR DESCRIPTION
**Pull request by vinayknl**
Using CompletableFuture so that Paginated Data loading can use Asynchronous loading.

### CODE REVIEW

**Comment by yarinvak** [comment]
Is it conflicts if someone doesn't want to use it asynchronious?

**Comment by vinayknl** [comment]
@yarinvak It makes sense to keep the original behavior as it is and add asyn as optional. So, added a wrapper and an option to set async in the annotation (defaults to false). Please review again.
Thanks,
Vinay

**Comment by guy120494** [comment]
Please add some tests to make sure that `AsyncConnectionDataFetcher` works (you can have the same tests as the regular `ConnectionDataFetcher`, just to see that it does what it is supposed to do)

**Comment by vinayknl** [comment]
I have added a test to ensure both sync and async way fetches data. I am not sure if we need a way to check if this is really async. Please check and let me know if any additional tests are desirable.

**Pull request merged**
