### PR TITLE
support static methods

### PR DESCRIPTION
**Pull request by nmn**
In continuation to the previous PR. Now you can use static methods on classes as dataFetchers that get invoked on null.

### CODE REVIEW

**Comment by nmn** [comment]
Sorry, need to add another test.

**Comment by yrashk** [comment]
Thanks!  💙

**Comment by nmn** [comment]
that was fast!

**Comment by yrashk** [comment]
I follow http://rfc.unprotocols.org/1/C4 — the goal is to give everybody a right to contribute and merge fast. The project hasn't adopted it formally yet, like other projects of mine [most notably https://github.com/eventsourcing/es4j] — mostly because I am lazy. Either way, my goal is to make contributors' experience awesome.

**Pull request merged**
