### PR TITLE
Add support for graphql-java v11

### PR DESCRIPTION
**Pull request by sergehuber**
Here is an update to migrate to graphql-java 11. I didn't have much time to test but all the unit tests seems to run.

The main point that needs review is the changes in the AsyncConnectionDataFetcher as I'm not an expert with the CompletableFutures

### CODE REVIEW

**Comment by sergehuber** [comment]
Not sure why the build is failing it works fine locally. Maybe an issue with the build platform ? Also when I click on details I get a 404.

**Comment by sergehuber** [comment]
Ah now the details work again and I get : 
"Google Cloud Platform project is not set up correctly for this GitHub app. Please reinstall the app and go through the setup flow again"

**Comment by yarinvak** [comment]
Yea there's some problem with the ci configuration.
I tried to fix this.
Can you open a new PR please?

**Comment by sergehuber** [comment]
Ok I'll try again

**Pull request closed without merging**
