### PR TITLE
Add support for graphql-java v11

### PR DESCRIPTION
**Pull request by sergehuber**
This PR contains updates to support graphql-java version 11.0

### CODE REVIEW

**Comment by sergehuber** [comment]
Seems like it failed again. It seems almost immediate.

**Comment by guy120494** [comment]
@yarinvak please have a look at this

**Comment by sergehuber** [comment]
If you need I can open PRs again to do more testing.

**Comment by yarinvak** [comment]
I have uninstalled the Google Cloud build. Can you try again? @sergehuber

**Comment by sergehuber** [comment]
Sorry I missed your reply. Will close this one and try again.

**Pull request closed without merging**
