### PR TITLE
(deps) Updating to latest graphql-java:17.1 library

### PR DESCRIPTION
**Pull request by setchy**
Updating to the recently released [graphql-java:17.0 library](https://github.com/graphql-java/graphql-java/releases/tag/v17.0)

As part of 17.0, the following breaking changes occured
* The deprecated ` BatchedExecutionStrategy` was removed.  As such, I've removed `@GraphQLBatched`
* Non-standard scalars (BigInteger, BigDecimal, Char, Byte, Long, Short) were all removed.   This was communicated within the [15.0 release notes](https://github.com/graphql-java/graphql-java/releases/tag/v15.0) and was finalized in 17.0.  As such, I have removed the same in this PR

Appreciate any feedback

### CODE REVIEW

**Comment by setchy** [comment]
Not sure why its trying to run the `publish` step. @yrashk :)

**Comment by yarinvak** [comment]
Hey @setchy thanks for you contribution.
I'm not sure why you've removed the custom scalars? Can you elaborate on this?

**Comment by setchy** [comment]
Hi @yarinvak - no problems.

Re: the removal of the custom scalars, I have followed up again this morning on [this graphql-java 17.0 release discussion thread](https://github.com/graphql-java/graphql-java/discussions/2500#discussioncomment-1129737) as there seems to be a disconnect atm.

Initially there was no mention of the removal in the release notes.  The revised release notes suggest they are now homed in the [graphql-java-extended-scalars](https://github.com/graphql-java/graphql-java-extended-scalars/tree/master/src/main/java/graphql/scalars) project, but that too hasn't quite happened.  

Looks like the intention is to keep the 6 scalars though and re-home them.  So with that said, I'll look to update this PR once a new version of extended-scalars is available (will update to [graphql-java 17.1 ](https://github.com/graphql-java/graphql-java/releases/tag/v17.1) at the same time)

**Comment by setchy** [comment]
@yarinvak - PR updated.

**Comment by oliemansm** [comment]
@yarinvak Any chance of getting this PR merged and a release published?

**Comment by yarinvak** [comment]
Hey @setchy , I've merged your PR but then I had to revert it because tests failed.
Please pull changes from our development branch (I fixed the pipeline) and fix the failing tests, then create a new PR and I will merge.

Thanks for your contribution

**Pull request merged**
